version: 2
jobs:
  build:
    working_directory: ~/exthereum
    docker:
      - image: elixir:latest
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix test

